### ISSUE TITLE
AttributeError: 'svmem' object has no attribute 'wired'

### ISSUE THREAD

**Issue by x2x4com** [tronprotocol/tron-cli#17]
OS: ubuntu 16.04 LTS
Python: 3.7.2

```
Traceback (most recent call last):
  File "/usr/local/bin/tron-cli", line 5, in <module>
    troncli.cli.main()
  File "/usr/local/lib/python3.7/site-packages/troncli/cli.py", line 149, in main
    cbox.main([init, config, run, stop, status, quick, version])
  File "/usr/local/lib/python3.7/site-packages/cbox/cli.py", line 117, in main
    exitcode = executor(func, argv, input_stream, output_stream, error_stream)
  File "/usr/local/lib/python3.7/site-packages/cbox/executors.py", line 50, in _execute_multi_cmd
    return funcs_dict[subcmd](**func_kwargs)
  File "/usr/local/lib/python3.7/site-packages/cbox/cli.py", line 79, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/troncli/cli.py", line 126, in status
    status_handler.overall()
  File "/usr/local/lib/python3.7/site-packages/troncli/h_status.py", line 38, in overall
    self.phrase.convert_bytes(int(virt.wired)))
AttributeError: 'svmem' object has no attribute 'wired'
```

Test on ipython
```
In [1]: import psutil

In [2]: virt = psutil.virtual_memory()

In [3]: dir(virt)
Out[3]:
['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_asdict',
 '_fields',
 '_fields_defaults',
 '_make',
 '_replace',
 'active',
 'available',
 'buffers',
 'cached',
 'count',
 'free',
 'inactive',
 'index',
 'percent',
 'shared',
 'slab',
 'total',
 'used']
```

**Comment by x2x4com** [comment]
also tested on macos

```
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import psutil

In [2]: virt = psutil.virtual_memory()

In [3]: dir(virt)
Out[3]:
['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_asdict',
 '_fields',
 '_make',
 '_replace',
 '_source',
 'active',
 'available',
 'count',
 'free',
 'inactive',
 'index',
 'percent',
 'total',
 'used',
 'wired']
```

**Comment by wxue** [comment]
Thanks for reporting and test it out. I'm working on fixing this and test more on Ubuntu. Will release a new version within this week containing the fix and other improvements. 

Will update here when fix released.

**Comment by zottirik** [comment]
same issue on ubuntu 18.04.
which os can i use until update?
